import 'package:dartz/dartz.dart';
import 'package:naqaa/app/enums/statistics_date_enum.dart';
import 'package:naqaa/app/failure.dart';
import 'package:naqaa/domain/entities/statistic.dart';
import 'package:naqaa/domain/repositories/repository.dart';
import 'package:naqaa/domain/usecases/base_usecase.dart';
import 'package:naqaa/presentation/theme/app_colors.dart';

class GetStatisticsUsecase
    implements BaseUsecase<GetStatisticsUsecaseInput, List<StatisticEntity>> {
  final Repository _repository;
  GetStatisticsUsecase(this._repository);

  @override
  Future<Either<Failure, List<StatisticEntity>>> execute(
      GetStatisticsUsecaseInput input) async {
    switch (input.statisticsDate) {
      case StatisticsDate.today:
        return const Right([
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 1,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 11,
            tempLowest: 8,
            tempAverage: 9,
            tdsHighest: 400,
            tdsLowest: 2,
            tdsAverage: 100,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 3,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 3,
            waterQualityName: "VERY_BAD",
            waterQualityHex: "#FF6B00",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 5,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 2,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 1,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
        ]);
      case StatisticsDate.sevenDays:
        return Right([
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 2,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 11,
            tempLowest: 8,
            tempAverage: 9,
            tdsHighest: 400,
            tdsLowest: 2,
            tdsAverage: 100,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 1,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 4,
            waterQualityName: "VERY_BAD",
            waterQualityHex: "#FF6B00",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 3,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 4,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 2,
            waterQualityName: "VERY_BAD",
            waterQualityHex: "#FF6B00",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 3,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
        ]);
      case StatisticsDate.month:
        return Right([
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 3,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 11,
            tempLowest: 8,
            tempAverage: 9,
            tdsHighest: 400,
            tdsLowest: 2,
            tdsAverage: 100,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 2,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 1,
            waterQualityName: "VERY_BAD",
            waterQualityHex: "#FF6B00",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 5,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 2,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
        ]);
      case StatisticsDate.sixMonths:
        return Right([
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 1,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 11,
            tempLowest: 8,
            tempAverage: 9,
            tdsHighest: 400,
            tdsLowest: 2,
            tdsAverage: 100,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 1,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 3,
            waterQualityName: "VERY_BAD",
            waterQualityHex: "#FF6B00",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 2,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 4,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
          StatisticEntity(
            tempHighest: 34,
            tempLowest: 12,
            tempAverage: 22,
            tdsHighest: 829,
            tdsLowest: 239,
            tdsAverage: 400,
            phHighest: 11,
            phLowest: 5.5,
            phAverage: 6.7,
            waterQuality: 2,
            waterQualityName: "DANGER",
            waterQualityHex: "#FF0F0F",
          ),
        ]);
    }
    // TODO: implement execute
    throw UnimplementedError();
  }
}

class GetStatisticsUsecaseInput {
  final StatisticsDate statisticsDate;
  final String deviceId;
  GetStatisticsUsecaseInput({
    required this.statisticsDate,
    required this.deviceId,
  });
}
