// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiqWPGGtFh4gV9TgPnNaPTKvOZqjLAh4A',
    appId: '1:498611243368:web:4783999996b4fc6ea46edd',
    messagingSenderId: '498611243368',
    projectId: 'naqaa-2023',
    authDomain: 'naqaa-2023.firebaseapp.com',
    databaseURL: 'https://naqaa-2023-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'naqaa-2023.appspot.com',
    measurementId: 'G-JDEV9KH9ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXzDYfCViC9NbwoZL50ut-oGQTH3QGq4k',
    appId: '1:498611243368:android:7de1a5b0f795ea39a46edd',
    messagingSenderId: '498611243368',
    projectId: 'naqaa-2023',
    databaseURL: 'https://naqaa-2023-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'naqaa-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAoyuHPTSedjvXQGca89DarMxLs86P3Ck',
    appId: '1:498611243368:ios:ec3c8d828b0f3ddaa46edd',
    messagingSenderId: '498611243368',
    projectId: 'naqaa-2023',
    databaseURL: 'https://naqaa-2023-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'naqaa-2023.appspot.com',
    iosClientId: '498611243368-vuokjdb1816o9i3utmsf40m22kbo4pav.apps.googleusercontent.com',
    iosBundleId: 'com.example.naqaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAoyuHPTSedjvXQGca89DarMxLs86P3Ck',
    appId: '1:498611243368:ios:16f6a48fc31272dba46edd',
    messagingSenderId: '498611243368',
    projectId: 'naqaa-2023',
    databaseURL: 'https://naqaa-2023-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'naqaa-2023.appspot.com',
    iosClientId: '498611243368-50iqtiv6fchcl26hu8d2k6j3sjr4t7ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.naqaa.RunnerTests',
  );
}
